services:
    libation:
        image: mdhmatt/libate:latest
        container_name: libation
        stop_grace_period: 1m
        restart: on-failure
        volumes:
            - './Books:/config/Books'
            - './data:/config/Libation'
